playbook_version: 3.4.2
# ########## google site verifications ##########
# for example google65679391aa745584.html
_google_webmaster: ""
# ########## local config ##########
_local_config: "{{(ansible_local.config|default({})).general|default({})}}"
# ########## Features ##########
setup_server: yes
setup_nginx: yes
_setup_ssl: yes
_ssl_wildcard: no
setup_jupyter: yes
setup_theia: yes
metrics_server: no
# ########## Creds ##########
person_name: Aldous Huxley
contact_email: alex@ebalrefuckanal.de
#sysuser
rsys_creds: [ "rsys", "" ]
ruser_creds: [ "ruser", "" ]
#main user. (temp)
main_user: default
main_user_password: default
#system users
support_user: 'x011'
remote_user: 'x011'
#key for update manager to access server
support_key_file: './keys/support.pub'
support_key: "{{ lookup('file', support_key_file) }}"
# ########## Repos ##########
git_account: https://github.com/rockstat
repos:
  band_set: "{{git_account}}/band-services-set"
  dashboard: "{{git_account}}/dashboard.git"
  theia: "{{git_account}}/theia-ide-image.git"
  splash: "{{git_account}}/splash.git"
# ########## Domains ##########
domain: "{{tracker_domain|default(ansible_host)}}"
domains:
  app: 'app.{{domain}}'
  web: 'web.{{domain}}'
  grafana: 'grafana.{{domain}}'
  jupyter: 'jupyter.{{domain}}'
  theia: 'theia.{{domain}}'
  netdata: 'netdata.{{domain}}'
  httpdebug: 'httpdebug.{{domain}}'
subdomains: "{{ domains.keys()|list }}"
# ########## SSL ##########
    # email: "{{contact_email}}"
# domains for regular reques
domains_ssl:
  - email: '{{contact_email}}'
    domains: "{{[domain] + domains.values()|list|unique}}"
# _ssl_cert_dir: "/etc/letsencrypt/live"
_ssl_cert_fullchain: fullchain.cer
_ssl_cert_trust: cert.cer
_ssl_cert_key: priv.key
# ########## Images ##########
images_default:
  chproxy: rockstat/chproxy
  redis: redis:4-alpine
  logspout: gliderlabs/logspout
  ebaloger: rockstat/ebaloger
  anaconda: continuumio/anaconda3
  grafana: rockstat/grafana
  band: rockstat/band-base-py
  director: rockstat/director
  theia: rockstat/theia-ide
  front: rockstat/front
  chwriter: rockstat/chwriter
  heavyload: rockstat/heavyload
images: "{{images_default|combine(images_custom|default({}))}}"
# ########## Logs ##########
#loggly
_loggly_hostname: logs-01.loggly...
_loggly_api_key: 10bbf2d8...
#papertrail
_papertrail_hostname: logs7.pape....
#destination
_logspout_target: none
_logspout_enabled: yes
# ########## dirs ##########
home_dir: '/srv/platform'
data_dir: '{{home_dir}}/data'
etc_dir: '{{home_dir}}/etc'
build_dir: '{{home_dir}}/build'
images_dir: "{{home_dir}}/images"
dirs:
  front_custom_config: "{{data_dir}}/front_custom_config"
  chwriter_custom_config: "{{data_dir}}/chwriter_custom_config"
  chwriter_emergency: "{{data_dir}}/chwriter_emergency"
  band: "{{images_dir}}/band_base"
  band_set: "{{images_dir}}/band_set"
  rockme_set: "{{images_dir}}/rockme_set"
  director_data: "{{data_dir}}/director_data"
  user_images: "{{images_dir}}/user"
  workspace: "{{data_dir}}/workspace"
  notebooks: "{{data_dir}}/notebooks"
  uploads: "{{data_dir}}/uploads"
  grafana_data: "{{home_dir}}/grafana"
  splash: "{{home_dir}}/splash"
  well_known: "{{home_dir}}/well_known"
  dashboard: "{{home_dir}}/dashboard"
  ovpnkeys: "{{home_dir}}/ovpn_keys"
  acmedns: "{{home_dir}}/acmedns"
  acmesh: "{{home_dir}}/acmesh"
  certs: "{{data_dir}}/certs"
  clickhouse: "/srv/clickhouse"
  clickhouse_tmp: "/srv/clickhouse_tmp"
  clickhouse_log: "/var/log/clickhouse-server"
  redis: "/srv/redis"
create_dirs: ["{{images_dir}}", "{{build_dir}}", "{{data_dir}}", "{{etc_dir}}", "{{dirs.well_known}}","{{dirs.certs}}"]
# ########## ports ##########
ports:
  # services
  director: [10000, 8080]
  front: [10001, 8080]
  front_ws: [10002, 8082]
  heavyload: [10010, 8080]
  httpdebug: [19992]
  ebaloger_http: [8085, 8080]
  ebaloger_udp: [5055, 8090]
  # tools
  logspout: [8088, 80]
  grafana: [3000, 3000]
  jupyter: [8888, 8888]
  theia: [8887, 8000]
  theia_user: [8886, 8080]
  netdata: [19999]
  # servers
  http: [80]
  https: [443]
  letsencrypt: [8011, 80]
  openvpn: [8080, 1194]
  redis: [6379, 6379]
  s2svpn: [8079]
  clickhouse_tcp: [9000]
  clickhouse: [8123]
  chproxy: [9090, 9090]
  chronograf: [18888]
  influxhttp: [18086]
  influxtsb: [4242]
# Mem limits
anaconda_mem_limit: 2g
# ########## Docker ##########
# user defined docker network
docker_net_name: custom
docker_interface: docker1
docker_net_pattern: 172.16.25.* # will be converted to 172.16.25.0/24
docker_users: 
  - '{{support_user}}'
# calculable
docker_net: "{{docker_net_pattern|ip_p2n}}"
docker_host_ip: "{{docker_net|net_gw}}"
docker_netmask: "{{docker_net|ipaddr('netmask')}}"
docker_net_net: "{{docker_net|ipaddr('network')}}"
# default docker network
docker_defnet_pattern: 172.17.*
docker_defnet_net: "{{docker_defnet_pattern|ip_p2n}}"
# other params
docker_band_lbls: {inband: system}
_restart_policy: unless-stopped
# ########## Clients VPN ##########
covpn_keys_dir: '{{home_dir}}/ovpn_keys'
# ########## Server-server VPN ##########
s2s_vpn_connect: false
s2s_vpn_key: 'ovpn_keys/node{{vpn_id}}.ovpn'
s2s_vpn_net_pattern: 192.168.222.*
s2s_vpn_net: "{{s2s_vpn_net_pattern|ip_p2n}}"
s2s_vpn_host_ip: "{{s2s_vpn_net|net_gw}}"
# ########## Interfaces ##########
if_outer: "{{ansible_default_ipv4.address}}"
if_inner: "{{docker_host_ip}}"
local_nets: [ "127.0.0.0/8", "{{s2s_vpn_net}}", "{{docker_net}}", "{{docker_defnet_net}}" ]
etc_hosts: # also used in docker containers
  host: "{{if_inner}}"
# ########## Firewall ##########
disable_ipv6: true
firewall_rules:
  - { from_ip: '{{docker_net}}'}
  - { to_port: '{{ports.http.0}}'}
  - { to_port: '{{ports.https.0}}'}
  - { to_port: '{{ports.openvpn.0}}'}
# ########## Jupyter/anaconda packages ##########
# default
jup_with_conda_def: ["ujson"]
jup_with_pip_def: ["prodict", "arrow", "simplech", "asimplech"]
# additional
jup_with_conda: [""]
jup_with_pip: [""]
# todo: ability to specify additional packages for theia and others
# ########## ClickHouse ##########  
_clickhouse_profiles_custom:
  sys_prof: { max_memory_usage: 3000000000, use_uncompressed_cache: 0, load_balancing: random } 
  user_prof: { max_memory_usage: 2000000000, use_uncompressed_cache: 0, load_balancing: random }
_clickhouse_users_custom:
  - { name: "{{rsys_creds.0}}", password: "{{rsys_creds.1}}", networks: "{{ local_nets }}", profile: "sys_prof", quota: "default" }
  - { name: "{{ruser_creds.0}}", password: "{{ruser_creds.1}}", networks: "{{ local_nets }}", profile: "user_prof", quota: "default" }
_clickhouse_logger:
  level: trace
  log: "{{ dirs.clickhouse_log }}/clickhouse-server.log"
  errorlog: "{{ dirs.clickhouse_log }}/clickhouse-server.err.log"
  size: 50M
  count: 7
ch_db: stats
# ########## CH PROXY ##########
_chproxy_defs:
  max_concurrent_queries: 3
  allow_cors: yes
  max_queue_time: 30s
  max_execution_time: 30s
  max_queue_size: 100
  to_cluster: local
_chproxy_allowed_networks_default: "{{local_nets}}"
_chproxy_clusters_default:
  - name: local
    nodes: [ "{{if_inner}}:{{ports.clickhouse.0}}" ]
    users:
      - { name: readonly, password: "" }
      - { name: default, password: "" }
_chproxy_users_default:
  - { to_user: 'readonly', name: 'readonly', password: 'readonly'}
  - { to_user: 'default', name: 'default', password: 'default'}
# ########## CH Common ##########
_chp_dsn: "http://{{main_user}}:{{main_user_password}}@host:{{ports.chproxy.0}}/{{ch_db}}"
_chs_dsn: "http://{{main_user}}@host:{{ports.clickhouse.0}}/{{ch_db}}"
# ########## Common Envs ##########
containers_env_extra: {}
_containers_env:
  # **ATTENTION! You have to configure variables at Director's config too!**
  DOMAIN: "{{domain}}"
  HOST_ADDR: "{{if_inner}}"
  STATSD_HOST: "{{if_inner}}"
  LOG_LEVEL: "info"
  JSON_LOGS: 1
  NETWORK: "{{docker_net_name}}"
  REDIS_DSN: "redis://redis:6379"
  CH_DSN: "{{_chp_dsn}}"
  CHP_DSN: "{{_chp_dsn}}"
  CHS_DSN: "{{_chs_dsn}}"
containers_env: "{{_containers_env|combine(containers_env_extra)}}"
_director_env:
  PORT: "{{ports.director.1}}"
  IMAGES_PATH: "/images"
_theia_env:
  PORT_THEIA: "{{ports.theia.1}}"
  PORT_USER: "{{ports.theia_user.1}}"
# ########## NGINX COMMONS ##########
# configuration extra params
_nginx_proxy_params_extra: []
_nginx_sites_extra: {}
_nginx_front_extra: []
# common blocks
_nginx_listen: 
  - "listen 443 ssl http2"
_nginx_ssl:
  - ssl_certificate_key     {{dirs.certs}}/{{domain}}/{{_ssl_cert_key}}
  - ssl_certificate         {{dirs.certs}}/{{domain}}/{{_ssl_cert_fullchain}}
  - ssl_trusted_certificate {{dirs.certs}}/{{domain}}/{{_ssl_cert_trust}}
_nginx_nocache:
  - add_header 'Cache-Control' 'no-store; must-revalidate'
  - expires off
_nginx_auth:
  - 'auth_basic "Restricted"'
  - "auth_basic_user_file auth_basic/common"
_nginx_base_vh: "{{ _nginx_listen + _nginx_ssl }}"
_nginx_le_challenge:
  - "location /.well-known/ { auth_basic off; proxy_pass http://uletsencrypt; }"
# specific configurations
_nginx_forward_vh:
  - server_name {sd}.{{domain}}
  - "{{_nginx_le_challenge}}"
  - location / { proxy_pass http://u{sd}; }
  - "{{_nginx_auth}}"
  - "{{_nginx_base_vh}}"
_nginx_defvh_http:
  - server_name _http
  - listen 80 default_server
  - "{{_nginx_le_challenge}}"
  - location /stub_status { stub_status; allow 127.0.0.1; deny all; access_log off;}
  - location / { return 301 https://$host$request_uri; }
_nginx_defvh_https:
  - "server_name _https"
  - "{{_nginx_listen.0}} default_server"
  - "{{_nginx_ssl}}"
  - "root {{dirs.splash}}"
  - "{{_nginx_le_challenge}}"
  - "location / { try_files $uri $uri/index.html; }"
_nginx_front:
  - server_name {{domain}}
  - "{{_nginx_base_vh}}"
  - "root {{dirs.splash}}"
  - "{{_nginx_le_challenge}}"
  - location / { try_files $uri $uri/index.html @upstream; }
  - location @upstream { proxy_pass http://ufront; }
  - location /wss { proxy_pass http://ufront_ws; }
  - "{{_nginx_front_extra}}"
  - location /upload {
      client_max_body_size 10m;
      client_body_buffer_size 128K; 
      limit_except POST { deny all; }
      proxy_pass http://uheavyload; }
_nginx_dashboard:
  - server_name app.{{domain}}
  - "{{_nginx_base_vh}}"
  - "{{_nginx_auth}}"
  - "root {{dirs.dashboard}}/dist"
  - "{{_nginx_le_challenge}}"
  - location /api/ { proxy_pass http://udirector/; }
  - location /ws { proxy_pass http://uebaloger; }
  - location / { try_files $uri /index.html; }
_nginx_grafana:
  - server_name grafana.{{domain}}
  - "{{_nginx_le_challenge}}"
  - location / { proxy_pass http://ugrafana; }
  - location /public/ { auth_basic off; proxy_pass http://ugrafana; }
  - "{{_nginx_auth}}"
  - "{{_nginx_base_vh}}"
  - proxy_set_header X-WEBAUTH-USER $remote_user
  - proxy_hide_header Authorization
_nginx_netdata:
  - access_log off
  - "{{_nginx_forward_vh|flatten|map('replace','{sd}','netdata')|list}}"
_nginx_sites:
  def_https: "{{_nginx_defvh_https|flatten }}"
  def_http: "{{_nginx_defvh_http|flatten }}"
  front: "{{_nginx_front|flatten }}"
  dashboard: "{{_nginx_dashboard|flatten }}"
  grafana: "{{_nginx_grafana|flatten}}"
  theia: "{{_nginx_forward_vh|flatten|map('replace','{sd}','theia')|list}}"
  jupyter: "{{_nginx_forward_vh|flatten|map('replace','{sd}','jupyter')|list}}"
  netdata: "{{_nginx_netdata|flatten}}"
  httpdebug: "{{_nginx_forward_vh|flatten|map('replace','{sd}','httpdebug')|list}}"
_nginx_upstreams:
  - 'upstream ufront { server {{if_inner}}:{{ports.front.0}} weight=10; keepalive 32; }'
  - 'upstream ufront_ws { server {{if_inner}}:{{ports.front_ws.0}} weight=10; keepalive 128; }'
  - 'upstream udirector { server {{if_inner}}:{{ports.director.0}} weight=10; keepalive 8; }'
  - 'upstream uheavyload { server {{if_inner}}:{{ports.heavyload.0}} weight=10; keepalive 32; }'
  - 'upstream ugrafana { server {{if_inner}}:{{ports.grafana.0}} weight=10; keepalive 4; }'
  - 'upstream uebaloger { server {{if_inner}}:{{ports.ebaloger_http.0}} weight=10; keepalive 4; }'
  - 'upstream ujupyter { server {{if_inner}}:{{ports.jupyter.0}} weight=10; keepalive 4; }'
  - 'upstream unetdata { server {{if_inner}}:{{ports.netdata.0}} weight=10; keepalive 8; }'
  - 'upstream utheia { server {{if_inner}}:{{ports.theia.0}} weight=10; keepalive 8; }'
  - 'upstream uhttpdebug { server {{if_inner}}:{{ports.httpdebug.0}} weight=10; }'
  - 'upstream uletsencrypt { server {{if_inner}}:{{ports.letsencrypt.0}}; }'

# ########## Other things ##########
hostname: "{{inventory_hostname_short|default(inventory_hostname)}}"
# ########## Mailer config ##########
mailer_subj_key: "Ваши ключи OpenVPN ({{ domain }}) v{{ playbook_version }}"
mailer_subj_snip: "Сниппет для сайта ({{ domain }}) v{{ playbook_version }}"
