---
chproxy_container: chproxy
chproxy_docker_bind: 127.0.0.1:9090:9090
chproxy_docker_net: bridge
# chproxy_build_dir: 
# chproxy_build_path: "{{}}"


# User can define own allowed networks

chproxy_allowed_networks: []
chproxy_allowed_networks_default:
  - 127.0.0.0/24
chproxy_def_allow_cors: yes
chproxy_def_max_queue_time: 30s
chproxy_def_max_execution_time: 30s
chproxy_def_max_queue_size: 100
chproxy_def_max_concurrent_queries: 3

chproxy_def_user: default
chproxy_def_password: default
chproxy_def_dest_user: default
chproxy_def_cluster: default
chproxy_def_node: 127.0.0.1:8123
chproxy_def_cluster_nodes:
  - '{{chproxy_def_node}}'

chproxy_users: []
chproxy_users_default:
  - name: '{{chproxy_def_user}}'
    password: '{{chproxy_def_password}}'
    allow_cors: true
    to_cluster: '{{chproxy_def_cluster}}'
    to_user: '{{chproxy_def_dest_user}}'
    max_concurrent_queries: 2
    max_queue_size: 100
    max_queue_time: 30s
    max_execution_time: 30s

chproxy_clusters: []
chproxy_clusters_default:
  - name: '{{chproxy_def_cluster}}'
    nodes: '{{chproxy_def_cluster_nodes}}'
