
- import_role:
    name: dr.openvpn-server
  vars:
    openvpn_port: "{{ports.openvpn.0}}"
    openvpn_clients: 5
    openvpn_comp_lz4: yes
    openvpn_clients_net: "{{s2s_vpn_net}}"
    openvpn_push:
      - "route {{docker_net_net}} {{docker_netmask}}"
  tags: ['openvpn']
